version: '2'
services:
    data:
        image: silintl/data-volume:latest
        container_name: data
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        container_name: db
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: idpmgmt
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    testDb:
       image: silintl/mariadb:latest
       container_name: testDb
       ports:
           - "3306"
       environment:
           MYSQL_ROOT_PASSWORD: r00tp@ss!
           MYSQL_DATABASE: test
           MYSQL_USER: idpmgmt
           MYSQL_PASSWORD: idpmgmt

    api:
        build: ./
        container_name: api
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./local.env

    cli:
        image: silintl/php7:latest
        container_name: cli
        volumes_from:
            - data
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        working_dir: /data
        user: "${DOCKER_UIDGID}"
        env_file:
            - ./common.env
            - ./local.env
        command: ["true"]

    zxcvbn:
        image: wcjr/zxcvbn-api:1.0.0
        container_name: zxcvbn
        ports:
            - "3000"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.31.0/24
              gateway: 10.20.31.1

