version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: idpmgmt
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    testDb:
       image: silintl/mariadb:latest
       ports:
           - "3306"
       environment:
           MYSQL_ROOT_PASSWORD: r00tp@ss!
           MYSQL_DATABASE: test
           MYSQL_USER: idpmgmt
           MYSQL_PASSWORD: idpmgmt

    api:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        ports:
            - "8080:80"
        depends_on:
            - db
            - memcache1
            - memcache2
        env_file:
            - ./common.env
            - ./local.env

    cron:
        build: ./
        volumes_from:
            - data
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./local.env
        command: /data/run-cron.sh

    apitest:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
            # Keep test file from overwriting the local.php file on the host
            - ./application/common/config/local.test.php:/data/common/config/local.php
        ports:
            - "8000:80"
        depends_on:
            - testDb
            - memcache1
        env_file:
            - ./common.env
            - ./local.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            MEMCACHE_CONFIG1_host: memcache1
            MEMCACHE_CONFIG1_port: 11211
            MEMCACHE_CONFIG1_weight: 100

        command: ["/data/run-tests-api.sh"]

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        working_dir: /data
        #user: "${DOCKER_UIDGID}"
        env_file:
            - ./common.env
            - ./local.env
        command: ["true"]

    zxcvbn:
        image: wcjr/zxcvbn-api:1.1.0
        ports:
            - "3000"

    memcache1:
        image: memcached:1.4-alpine
        ports:
            - "11211:11211"

    memcache2:
        image: memcached:1.4-alpine
        ports:
            - "11212:11211"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.31.0/24
              gateway: 10.20.31.1

