version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: pwmgr
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    testDb:
       image: silintl/mariadb:latest
       ports:
           - "3306"
       environment:
           MYSQL_ROOT_PASSWORD: r00tp@ss!
           MYSQL_DATABASE: test
           MYSQL_USER: idpmgmt
           MYSQL_PASSWORD: idpmgmt

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_USER: idpmgmt
            PMA_PASSWORD: idpmgmt

    api:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        ports:
            - "8080:80"
        depends_on:
            - db
            - email
        env_file:
            - ./common.env
            - ./local.env

    cron:
        build: ./
        volumes_from:
            - data
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./local.env
        environment:
            AUTH_SAML_idpCertificate:
            AUTH_SAML_spCertificate:
            AUTH_SAML_spPrivateKey:
        command: /data/run-cron.sh

    apitest:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        ports:
            - "8000:80"
        depends_on:
            - testDb
        env_file:
            - ./common.env
            - ./local.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
        command: ["/data/run-tests-api.sh"]

    cli:
        image: silintl/php7:latest
        volumes_from:
            - data
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        working_dir: /data
        user: "${DOCKER_UIDGID}"
        depends_on:
            - email
        env_file:
            - ./common.env
            - ./local.env
        command: ["true"]

    email:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
            - emailcron
        env_file:
            - ./common.env
            - ./email.common.env
            - ./email.local.env
        ports:
            - "8082:80"

    emailcron:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
        env_file:
            - ./common.env
            - ./email.common.env
            - ./email.local.env
        command: /data/run-cron.sh

    emaildb:
        image: silintl/mariadb:latest
        env_file:
            - ./common.env
        environment:
            MYSQL_ROOT_PASSWORD: not-a-secret
            MYSQL_DATABASE: email
            MYSQL_USER: email
            MYSQL_PASSWORD: email

    zxcvbn:
        image: wcjr/zxcvbn-api:1.1.0
        ports:
            - "3000"

    brokerDb:
        image: silintl/mariadb:latest
        ports:
        - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_HOST: brokerDb
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass

    broker:
        image: silintl/idp-id-broker:latest
        ports:
        - "8083:80"
        depends_on:
        - brokerDb
        volumes:
        - ./run-broker.sh:/data/run-broker.sh
        working_dir: /data
        environment:
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            IDP_NAME: idp1
            MYSQL_HOST: brokerDb
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: dummy-root-password
            API_ACCESS_KEYS: abc123
            HELP_CENTER_URL: https://example.com/#/help
            PASSWORD_FORGOT_URL: https://example.com/#/forgot
            PASSWORD_PROFILE_URL: https://example.com/#/profile
            SUPPORT_EMAIL: support@example.com
            EMAIL_SIGNATURE: Dummy Signature for Tests
        command: whenavail brokerDb 3306 60 ./run-broker.sh

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.31.0/24
              gateway: 10.20.31.1

