version: '2'
services:
    data:
        image: silintl/data-volume:latest
        volumes:
            - ./application:/data
        user: "${DOCKER_UIDGID}"

    db:
        image: silintl/mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: pwmgr
            MYSQL_USER: idpmgmt
            MYSQL_PASSWORD: idpmgmt

    testDb:
       image: silintl/mariadb:latest
       environment:
           MYSQL_ROOT_PASSWORD: r00tp@ss!
           MYSQL_DATABASE: test
           MYSQL_USER: idpmgmt
           MYSQL_PASSWORD: idpmgmt

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            PMA_USER: idpmgmt
            PMA_PASSWORD: idpmgmt

    api:
        build: ./
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - db
            - email
        env_file:
            - ./common.env
            - ./local.env

    cron:
        build: ./
        volumes_from:
            - data
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./local.env
        command: /data/run-cron.sh

    apitest:
        build: ./
        volumes_from:
            - data
        depends_on:
            - testDb
            - zxcvbn
        env_file:
            - ./common.env
            - ./test.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
            ID_BROKER_baseUrl: http://broker
        command: ["/data/run-tests-api.sh"]

    unittest:
        build: ./
        volumes_from:
            - data
        volumes:
            - ./dockerbuild/dev-ldap.conf:/etc/ldap/ldap.conf
        depends_on:
            - testDb
        env_file:
            - ./common.env
            - ./test.env
            - ./codeship.env
        environment:
            MYSQL_HOST: testDb
            MYSQL_DATABASE: test
            APP_ENV: test
            ID_BROKER_baseUrl: http://broker
        command: ["/data/run-tests.sh"]

    cli:
        image: silintl/php7:7.2
        volumes_from:
            - data
        volumes:
            - ${COMPOSER_CACHE_DIR}:/composer
        working_dir: /data
        user: "${DOCKER_UIDGID}"
        env_file:
            - ./common.env
            - ./local.env
        command: ["true"]

    email:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
            - emailcron
        env_file:
            - ./email.common.env
            - ./email.local.env
        ports:
            - "8082:80"

    emailcron:
        image: silintl/email-service:develop
        depends_on:
            - emaildb
        env_file:
            - ./email.common.env
            - ./email.local.env
        command: /data/run-cron.sh

    emaildb:
        image: silintl/mariadb:latest
        env_file:
            - ./email.common.env
        environment:
            MYSQL_ROOT_PASSWORD: not-a-secret

    zxcvbn:
        image: wcjr/zxcvbn-api:1.1.0

    brokerDb:
        image: silintl/mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker

    broker:
        image: silintl/idp-id-broker:develop-4.0
        ports:
            - "8083:80"
        depends_on:
            - brokerDb
        volumes:
            - ./run-broker.sh:/data/run-broker.sh
        environment:
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            EMAILER_CLASS: \Sil\SilIdBroker\Behat\Context\fakes\FakeEmailer
            IDP_NAME: idp1
            MYSQL_HOST: brokerDb
            MYSQL_DATABASE: broker
            MYSQL_USER: broker
            MYSQL_PASSWORD: broker
            API_ACCESS_KEYS: abc123
            HELP_CENTER_URL: https://example.com/#/help
            PASSWORD_FORGOT_URL: https://example.com/#/forgot
            PASSWORD_PROFILE_URL: https://example.com/#/profile
            SUPPORT_EMAIL: support@example.com
            EMAIL_SIGNATURE: Dummy Signature for Tests
            APP_ENV: test
        command: ./run-broker.sh

    ldap:
        build: ./dockerbuild/ldap
        env_file:
            - ./local.env

    ldapload:
        build: ./dockerbuild/ldap
        depends_on:
            - ldap
        working_dir: /data
        command: ./load_ldap.sh

    raml2html:
        image: mattjtodd/raml2html
        volumes:
            - ./api.raml:/api.raml
            - ./api.html:/api.html
        command: -i api.raml -o api.html

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 10.20.31.0/24
              gateway: 10.20.31.1

